name = "dishonest-ethereum-rpc-provider"
type = "javascript"
workers_dev = true
usage_model = "unbound"
compatibility_date = "2021-12-30"

[build]
command = "yarn && yarn build"

[build.upload]
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [
  { name = "client_logs", class_name = "ClientLog" }
]

[[migrations]]
tag = "v1"
new_classes = ["ClientLog"]
